import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import CoreLayout from '@/components/layout/core-layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'bg-neutral-50 dark:bg-neutral-950 text-neutral-950 dark:text-neutral-50')}>
        <CoreLayout>{children}</CoreLayout>
      </body>
    </html>
  )
}
